"use client";
import type { Metadata } from "next";
import { ArtistSidebar } from "@/components/ArtistSidebar";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import Link from "next/link";

import "./../globals.css";
import { Input } from "@/components/ui/input";
import { Bell, ChevronDown, Search } from "lucide-react";

import { MelodiousProvider } from "@/contexts/melodious";
import ConnectWallet from "@/components/ConnectWallet";
import { Toaster } from "react-hot-toast";

// export const metadata: Metadata = {
//   title: "Artist | Melodious Music Streaming Platform ",
//   description: "Generated by create next app",
// };

export default function ArtistLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <MelodiousProvider>
        <SidebarProvider>
          <ArtistSidebar />
          <SidebarInset className="bg-main-content-gradient bg-cover bg-center">
            <header className="sticky top-0 z-10 bg-[#2A174A] flex h-16 shrink-0 items-center gap-2 transition-[width,height] ease-linear group-has-[[data-collapsible=icon]]/sidebar-wrapper:h-12 drop-shadow-lg">
              <div className="flex justify-between items-center gap-2 px-4 w-full">
                <div className="w-2/3 flex  items-center">
                  <SidebarTrigger className="-ml-1 text-white" />
                  <div className="relative">
                    <Input
                      type="text"
                      className="pl-10 pr-4 py-2 border-[#D1E1E11C] rounded-lg focus:outline-none focus:ring-2 focus:ring-gray-500 bg-[#323D4E] text-gray-200 w-full h-[35px] sm:w-[300px] md:w-[350px] lg:w-[426px] xl:w-[400px] 2xl:w-[400px]"
                      placeholder="Search..."
                    />
                    <div className="absolute inset-y-0 left-0 bottom-0 flex items-center pl-3 pointer-events-none">
                      <Search className="w-5 h-5 text-gray-500" />
                    </div>
                  </div>
                </div>
                <div className="flex items-center gap-4">
                  <Bell size={24} fill="blue" className="text-white" />

                  {/* <Link
                    href="/artist/wallet"
                    className="bg-[#950944] text-white p-2 rounded"
                  >
                    Wallet
                  </Link> */}

                  <div className="flex items-center gap-2">
                    <ConnectWallet />
                  </div>
                </div>
              </div>
            </header>
            <main>{children}</main>
            <Toaster />
          </SidebarInset>
        </SidebarProvider>
      </MelodiousProvider>
    </div>
  );
}
